services:
  ameya-web-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    env_file:
      - .dev.env
    networks:
      - appflyte

networks:
  appflyte:
      external: true